create table if not exists public.wishlist_items (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  "guestId" bigint not null,
  "cabinId" bigint not null,
  constraint "wishlist_items_guestId_fkey"
    foreign key ("guestId") references public.guests (id) on delete cascade,
  constraint "wishlist_items_cabinId_fkey"
    foreign key ("cabinId") references public.cabins (id) on delete cascade,
  constraint wishlist_items_guest_cabin_key unique ("guestId", "cabinId")
);

alter table public.wishlist_items enable row level security;

-- Wishlist access goes through the server-only Supabase secret key after the
-- NextAuth session has been checked. No anon/authenticated RLS policy is needed.
revoke all on table public.wishlist_items from anon, authenticated;
grant all on table public.wishlist_items to service_role;

revoke all on sequence public.wishlist_items_id_seq from anon, authenticated;
grant all on sequence public.wishlist_items_id_seq to service_role;
